### PR TITLE
Fix destroy() method on Group

### PR DESCRIPTION
**Pull request by jtlan**
The list of `Component`s in the implementation of `_forEach()` should be a shallow copy.

### CODE REVIEW

**Comment by bluong** [comment]
Provide QE with how to test this

**Comment by jtlan** [comment]
The QE test would pretty much be identical to the unit test: `destroy()` should destroy the sub-`Component`s of `Group.

Fiddle: http://jsfiddle.net/2kqcyed2/

**Comment by crmorford** [comment]
Why did this fiddle destroy c1 (http://jsfiddle.net/2kqcyed2/1/) but not c2?

**Comment by jtlan** [comment]
To explain:
If `destroy()` didn't operate on a shallow copy of the array, the list of `Component`s would mutate during the `forEach()` loop, similar to the following code:
```Javascript
arr = [0,1,2,3,4,5,6,7,8,9];
arr.forEach(function(d, i) { console.log(d); arr.splice(i,1); })
```

Using a shallow copy fixes the problem:
```Javascript
arr.slice().forEach(function(d, i) { console.log(d); arr.splice(i,1); })
```

**Pull request merged**
