### PR TITLE
Tick Label Shear

### PR DESCRIPTION
**Pull request by themadcreator**
Adds `tickLabelShearAngle` property to `CategoryAxis` to enable shearing of long tick label text.

### CODE REVIEW

**Comment by themadcreator** [comment]
Check it out!

https://142-16149854-gh.circle-artifacts.com/0/home/ubuntu/plottable/quicktests/dev/index.html#interactions/angle_text

**Review by hellochar — APPROVED** [review]

**Comment by hellochar** [comment]
Looks like there's some moments where the axis labels are all disappearing before downsampling takes effect:

image

image

image

**Comment by themadcreator** [comment]
I wonder if the default downsample threshold is just a little bit too small

**Comment by hellochar** [comment]
Yeah... I wonder if we should rework how downsampling works to generically detect when the text isn't drawn, versus using 15px always. Filed #3229

**Pull request merged**
