### PR TITLE
Removed params.json

### PR DESCRIPTION
**Pull request by aicioara**
Old file, not used anywhere, unsure if needed.

### CODE REVIEW

**Comment by aicioara** [comment]
Was added here 1 year ago 
https://github.com/palantir/plottable/pull/715

**Comment by jtlan** [comment]
> `"note":"Don't delete this file! It's used internally to help with page regeneration."`

I think this was probably for when the Plottable website was hosted on the **gh-pages** branch from this repository, before it was moved to its own repo.

**Comment by aicioara** [comment]
I see. I was thinking so, but was unsure.

**Comment by aicioara** [comment]
[NOQE] as no JS file changes

**Pull request merged**
