### PR TITLE
[Axis.Numeric] - Removing showEndTicklabel

### PR DESCRIPTION
**Pull request by bluong**
From my reading of this and removal of the appropriate code, it seems like this endpoint... did absolutely nothing.  Removing this dead code

### CODE REVIEW

**Comment by aicioara** [comment]
Looked through this. I am not really sure who uses what from our public API, so can't really +1 it. Maybe @jtlan should have an opinion. 
Anyway, since we delete this, why do we keep `abstractAxis.showEndTickLabels()` ? 

I am also curious what was it supposed to do, can't really make it work anyway.

**Comment by aicioara** [comment]
Oh, I see, this is the setter/getter of a field that is never really actually used. I am now wondering why is this the case, when did it become obsolete and why was it not removed right then in the first place?

Anyway, ideally we should either make it work or delete `abstractAxis.showEndTickLabels()` as well, as it is in the exact same situation.

**Comment by jtlan** [comment]
It became obsolete because we put a CSS class on the end ticks, so you could hide it like this:
```CSS
```

**Comment by jtlan** [comment]
`abstractAxis.showEndTickLabels()` does seem to be used though, so we should probably leave it. Maybe we should move it to `Axes.Numeric` though?

**Pull request closed without merging**
