### PR TITLE
Dispatcher revamp

### LINKED ISSUE #837: Plottable.Core.KeyEventListener sets an un-namespaced listener on entire document
this causes a quicktest failure (key_interaction.js, pressing 'a' only resets the domain for the right test, and has no effect on the left, #782) and is a bad idea generally.

steps:
 - [ ] - Namespace it to Plottable so that it doesnt conflict w/ other libs
 - [ ] - namespace it on a per-branch basis to solve the quicktest problem.

### LINKED ISSUE #1490: Zooming on IE9 causes hover to work incorrectly
Repro: http://jsfiddle.net/wu91q6wy/

Try hovering over the points. Then zoom in with `Ctrl`+`+` and note how the hitbox area for the scatterplot no longer aligns with the points in the plot.

### LINKED ISSUE #1560: <svg>-wide Dispatcher.Mouse
Convert `Dispatcher.Mouse` to use a single listener attached to the root `<svg>`, which then proxies the events to any `Dispatcher`s/`Interaction`s that are want the information.

Dependent on #1559, so that event positions relative to a `Component` can be inferred.

### PR DESCRIPTION
**Pull request by jtlan**
Moved dispatchers to the new architecture.

This should maintain the existing functionality, but fix the CSS zoom (#1644) and IE9 zoom bugs (#1490) for `Hover` and `Key` interactions. Should also solve #837.

Also puts us on the path to resolving #1427, by removing the need for hitboxes.

Close #837.
Close #1490.
Close #1560.

### CODE REVIEW

**Comment by jtlan** [comment]
@bluong @rcchen You can re-review, but the pieces of this have passed Dev CR before.

**Comment by bluong** [comment]
```
This should maintain the existing functionality, but fix the CSS zoom (#1644) and IE9 zoom bugs (#1490) for Hover and Key interactions. Should also solve #837.

Also puts us on the path to resolving #1427, by removing the need for hitboxes.
```

I don't think the issues would get parsed correctly to close.  Maybe do a fixes ___ for each just in case?

**Comment by bluong** [comment]
@jtlan We might want to change the keyDispatcher API to keyDown instead of keydown

**Comment by jtlan** [comment]
@bluong wrote:
> I don't think the issues would get parsed correctly to close.  Maybe do a fixes ___ for each just in case?

Not all of them should be closed, so that's probably fine...?

**Comment by crmorford** [comment]
Haven't played with IE yet, but CSS zooming + hover is working!

**Comment by rcchen** [comment]
@crmorford wrote:
> Haven't played with IE yet

famous last words

**Comment by bluong** [comment]
@jtlan wrote:
> Not all of them should be closed, so that's probably fine...?

Are you manually going to close the issues that should be closed after this goes in?

**Comment by crmorford** [comment]
DRUMROLL PLEASE
http://jsfiddle.net/8brgqrnr/1/
This still works....
In IE...
With CSS scaling (bigger OR smaller than 1)...
And ctrl ++ (or ctrl --)
On every single type of plot

Good Job Justin #1 Gold star

**Comment by rcchen** [comment]
:star: :star: :star: :star: :star:

**Pull request merged**
