### PR TITLE
[PanZoomInteraction] - add API for Pan Limits

### PR DESCRIPTION
**Pull request by bluong**
Adding API and incredibly basic functionality for setting / getting.  Does not have an impact

API Additions:

``` typescript
/**
  * Gets the minimum allowable domain value for the scale.
  *
  * Note that this will mainly work on scales that work linearly like Linear Scale and Time Scale.
  *
  * @param {QuantitativeScale<any>} quantitativeScale The scale to query
  * @returns {D} The minimum domain value for the scale.
  */
minDomainValue<D>(quantitativeScale: QuantitativeScale<D>): D;
/**
  * Sets the minimum allowable domain value for the scale.
  *
  * Note that this will mainly work on scales that work linearly like Linear Scale and Time Scale.
  *
  * @param {QuantitativeScale<any>} quantitativeScale The scale to query
  * @param {D} minDomainValue The minimum domain value for the scale.
  * @returns {Interactions.PanZoom} The calling PanZoom Interaction.
  */
minDomainValue<D>(quantitativeScale: QuantitativeScale<D>, minDomainValue: D): Interactions.PanZoom;
/**
  * Gets the maximum allowable domain value for the scale.
  *
  * Note that this will mainly work on scales that work linearly like Linear Scale and Time Scale.
  *
  * @param {QuantitativeScale<any>} quantitativeScale The scale to query
  * @returns {D} The maximum domain value for the scale.
  */
maxDomainValue<D>(quantitativeScale: QuantitativeScale<D>): D;
/**
  * Sets the maximum allowable domain value for the scale.
  *
  * Note that this will mainly work on scales that work linearly like Linear Scale and Time Scale.
  *
  * @param {QuantitativeScale<any>} quantitativeScale The scale to query
  * @param {D} maxDomainExtent The maximum domain value for the scale.
  * @returns {Interactions.PanZoom} The calling PanZoom Interaction.
  */
maxDomainValue<D>(quantitativeScale: QuantitativeScale<D>, maxDomainValue: D): Interactions.PanZoom;
```

### CODE REVIEW

**Comment by bluong** [comment]
First step from #2737

**Comment by jtlan** [comment]
Can we update the module naming as a separate commit to avoid the huge diff?

**Comment by MadsMadsDk** [comment]
I've been trying to implement this PR in my current project, where I have a timescale for the x-axis, but setting minDomainValue and maxDomainValue doesn't seem to be enforced by the PanZoom-interaction. Am I doing something wrong or is this a bug?

Here's an example: http://plottable.ulso.io/

Source:

``` javascript
"use strict";

var xScale = new Plottable.Scales.Time();
var yScale = new Plottable.Scales.Linear();

var xAxis = new Plottable.Axes.Time(xScale, "bottom");
var yAxis = new Plottable.Axes.Numeric(yScale, "left");

var plots = new Plottable.Components.Group();
var panZoom = new Plottable.Interactions.PanZoom(xScale, null);
var gridlines = new Plottable.Components.Gridlines(xScale, yScale);

var start = new Date("October 1 2015");
var end = new Date("October 2 2015");

panZoom.minDomainValue(xScale, start);
panZoom.maxDomainValue(xScale, end);

xScale.domain([start, end]);
xScale.onUpdate(function (scale) {
  console.log('min', panZoom.minDomainValue(scale));
  console.log('max', panZoom.maxDomainValue(scale));
});

plots.append(gridlines);

var table = new Plottable.Components.Table([[null, null], [yAxis, plots], [null, xAxis]]);

table.renderTo("svg#example");

d3.json("api/spotPriceforecast.json", function (error, data) {
  var parseDate = d3.time.format("%Y%m%d").parse;

  var dataSet = new Plottable.Dataset();
  dataSet.data(data);

  var plot = new Plottable.Plots.Line()
    .addDataset(dataSet)
    .x(function (d) { return new Date(d.StartDate); }, xScale)
    .y(function (d) { return d.PriceDKK; }, yScale)
    .attr('stroke', 'lightgreen');

  panZoom.attachTo(plot);

  plots.append(plot);
});

d3.json("api/spotPrice.json", function (error, data) {
  var parseDate = d3.time.format("%Y%m%d").parse;

  var dataSet = new Plottable.Dataset();
  dataSet.data(data);

  var plot = new Plottable.Plots.Line()
    .addDataset(dataSet)
    .x(function (d) { return new Date(d.StartDate); }, xScale)
    .y(function (d) { return d.PriceDKK; }, yScale)
    .attr('stroke', 'cornflowerblue');

  panZoom.attachTo(plot);

  plots.append(plot);
});
```

**Comment by themadcreator** [comment]
Unfortunately, @MadsMadsDk is right. This doesn't appear to actually constrain the pan zoom.

Fortunately, I have implemented this feature in another PR (#3111), which is now merged! I'm closing this PR since it's no longer needed.

**Pull request closed without merging**
