### PR TITLE
Gridlines on Scales.Category

### LINKED ISSUE #1289: Gridlines on Scale.Category

### PR DESCRIPTION
**Pull request by aicioara**
Closes #1289

Consider the scenario of scatter plot + gridlines on category scale. It should be valid IMO. 

**Fiddle**: http://jsfiddle.net/haku8pmk/1/
**QE Notes:** Before, using gridlines with a Category Scale, just threw an error (watch console). Now it should work as expected.

### CODE REVIEW

**Comment by jtlan** [comment]
We probably want to get some details about who this was for and why they needed it. Part of the issue here is that for `Bar` `Plot`s, people might want the lines to come out between the ticks or something.

**Comment by aicioara** [comment]
I really doubt we can remember something from 2014. Especially since the issue does not seem well documented. My suggestion is won't fix until someone actually requests this feature

**Comment by bluong** [comment]
In retrospect, we should have documented that issue better...

**Comment by aicioara** [comment]
Closing... Issue is too old and poorly documented. If the feature is needed, it will be requested again and we can refer to this.

**Pull request closed without merging**
