### PR TITLE
[Typescript] - upgrade to use 1.5-beta

### PR DESCRIPTION
**Pull request by bluong**
Developer actions:
* Please run `npm install` to upgrade to the latest compiler after this branch merges to develop.

QE:
* Regression pass please on the overall code.  We updated a tool that generates the entire JS.

### CODE REVIEW

**Comment by bluong** [comment]
We updated a tool that affects our JS.  We should have a QE pass.

**Comment by crmorford** [comment]
my tests look ok

**Comment by aicioara** [comment]
Do we want to upgrade to the beta? After recent discussions about backwards compatibility with 1.4 it seems more like an overhead (i.e. figure out if a feature we use has been introduced in 1.5 or not)

**Comment by bluong** [comment]
Based on prior discussion and the fact that 1.5 is hopefully due to be out any day now, let's hold off on the upgrade

**Comment by aicioara** [comment]
This was second attempt. 3rd time lucky

**Pull request closed without merging**
