### PR TITLE
[Gitignore / Travis] - Ignore bower components

### PR DESCRIPTION
**Pull request by bluong**
The reason why `node_modules` is ignored while `bower_components` seems to be because Travis will willingly run `npm install` when we push our stuff to Travis.  Thus, if have Travis run `bower install`, we do not necessarily need `bower_components` to be checked in either.

Reference: http://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle

### CODE REVIEW

**Comment by jtlan** [comment]
Any changes in workflow for developers?

**Comment by bluong** [comment]
This should require no changes in workflow.  We just need to be more dutifully responsible when changing the `bower_components` in terms of communication.

**Comment by jtlan** [comment]
As in, people will have to run `bower_install` in the future if packages are updated/changed?

**Comment by bluong** [comment]
Yeap

**Comment by jtlan** [comment]
This looks good, but I think we should check with similar projects here. Consider it a conditional +1.

**Comment by bluong** [comment]
After discussion with other collaborators, it seems that removing the `bower_components` directory from the repo runs into 2 problems:
* Developers need to be kept up to date with this directory.
* Build systems need to import `bower_components` which can be flaky.

To conclude, we should not move forward with this until we have a really compelling reason for this.

**Pull request closed without merging**
