### PR TITLE
[Legend] - legend.scale -> legend.colorScale

### PR DESCRIPTION
**Pull request by bluong**
By definition, a Legend is a visualization of a colorScale.  It should be named such

### CODE REVIEW

**Comment by jtlan** [comment]
If it's implied that the `Scale` is a `Scales.Color`, why would we need to name the variable as such? On `Axes.Time` we don't call the `Scale` parameter "`timeScale`", for example.

**Comment by aicioara** [comment]
But the `Axes.Time` does not have a method called `scale()`. This one does. Argument name is not as important as method name, and I believe the change makes sense. 

However, we have to watch out for inconsistencies (if there are any I did not spot)

**Comment by jtlan** [comment]
Makes sense. Also might be helpful if we want to add a `radiusScale()` API point later or something.

**Comment by bluong** [comment]
Simple rename.  NOQE

**Pull request merged**
