### PR TITLE
More tests

### PR DESCRIPTION
**Pull request by crmorford**
Just adding tests to the overlay page!

### CODE REVIEW

**Comment by rcchen** [comment]
lgtm :+1:

**Comment by bluong** [comment]
@rcchen After using them for a little bit, we found that working with comments made in specific commits has been quite the hassle (Github has pretty poor support for this) for the following reasons:
1) The code associated with the comment is not shown in this main page
2) If that piece of code changes later, the comment can be outdated but it can be hard to tell
3) The comments show up other pull requests (like the release prs)

It's mainly on the fault of github I think, but please place the comments either here on the main page or on the files changed tab.

**Comment by crmorford** [comment]
hey guys! what do I do since the last travis build failed?

**Comment by bluong** [comment]
Judging from the console logs, it seems the errors were mainly from tunnel connection issues, which can be really flaky at times.  At times like this, just retrigger the build.

**Pull request merged**
