### PR TITLE
use nested modules

### PR DESCRIPTION
**Pull request by bluong**
Based on the last answer here https://stackoverflow.com/questions/12737942/does-typescript-support-namespace , we can nest our modules such that

```typescript
module A {
  export module B {
  }
}
```

can be rewritten as

```typescript
module A.B {
}
```

This is somewhat exactly what we have been looking for in our files to prevent the annoying indentation.

It also exposes a few awkward pieces of organization when placing exported types and interfaces.

QE: This should not affect anything from a user perspective, mainly taking advantage of one aspect of Typescript.  Regression pass please

### CODE REVIEW

**Comment by jtlan** [comment]
Isn't the nested version more semantically correct though? I note the non-nested version injects extra instances of "`Plottable.`" where it wasn't required before.

**Comment by bluong** [comment]
Both versions of Plottable mean exactly the same thing semantically.  The main difference is compactness in writing (which was something we wanted for a while).

Also I suspect that the new version changes is because the according type is not declared in the same module declaration.

**Comment by jtlan** [comment]
I'm just concerned that this increases the size of our JS file while not providing benefits other than allowing us to fix our module indenting, which usually isn't something I'm worried about unless I'm making a new file.

**Comment by bluong** [comment]
You can see in the diff that this increases the size of our JS file by 12 lines, which is not big at all considering that the JS File is on the order of 6000 lines.  The two things that I find to be most relevant is that:
* It directly places the source code in the exact module that it should reside in (No need to do `module Plottable { export module Foo {`) to be in the correct module context.  Just do `module Plottable.Foo` which is much more concise.)
* By directly placing the source code in the right module, it also exposes a messiness in the code where if we did this before, we would have spotted more immediately and prevented.  Did you know that `Interaction`s placed their callback type signatures in the top level parent namespace?  This seems incorrect.

**Pull request merged**
