### PR TITLE
[Scales.ModifiedLog] - removing showIntermediateTicks

### PR DESCRIPTION
**Pull request by bluong**
In a recent API Discussion, there was talk about the use of this idea and talk about removing it.

### CODE REVIEW

**Comment by jtlan** [comment]
Related: #1762.

**Comment by crmorford** [comment]
Let's see if we can find out why we did this and who wanted it, and if they still need it.

**Comment by jtlan** [comment]
This feature was originally added in #710 (commit 8d6e26e); I think it was built for Slate. No one has touched it since then, so I think it's a fairly safe default. A `TickGenerator` can be used to generate more specific behavior.

**Comment by dbt** [comment]
I'm punting this to rc5 since we've already released rc4.  Is this ready to merge?

**Comment by jtlan** [comment]
@dbt @christinaforney was looking to see if people still cared about this feature. I think it's safe to remove it, since `TickGenerator`s can be used to fill the gap in functionality, if it was important to anyone.

**Comment by jtlan** [comment]
[+1], since `TickGenerator`s are a better way to accomplish this. For that matter, can we set the default `TickGenerator` on `ModifiedLog` to only produce powers of the base?

**Pull request merged**
