### PR TITLE
Remove Constructor instance methods

### PR DESCRIPTION
**Pull request by bluong**
QE: Regression pass at most.  This is mainly architectural cleanup.

After some time, we found that there was a pain point in terms of awkward bugs arising from the fact that instance methods are called from the constructor.  The reason is because one can argue that until a constructor is fully finished, the object is not fully constructed and the instance variables are not all fully set yet.  The problem with instance methods is that the many of them tend to assume that the object is in a fully constructed state before executing, which can lead to weird bugs if instance methods have not been initialized before the instance method is called.

### CODE REVIEW

**Comment by crmorford** [comment]
This actually broke the clustered_bar quicktest

**Comment by crmorford** [comment]
looks like legends now merge into the middle of a plot, instead of at the top right.

**Comment by crmorford** [comment]
Lets figure out why the no_data no_renderer scales are different, otherwise this looks fine now

**Comment by bluong** [comment]
I'll use this branch in order to make a new branch that will try to make constructors cleaner

**Pull request closed without merging**
