### PR TITLE
[Reference.ts] - Remove reference lines

### PR DESCRIPTION
**Pull request by bluong**
Removing these lines seems to have no effect on the compiler.  My personal guess is that `reference.ts` has already defined the files that need to be compiled and that restating it is redundant?

### CODE REVIEW

**Comment by aicioara** [comment]
Agree. Can you double check the following: 

- Without the PR, while `grunt watch`ing, try to change a single file (any src/**/*.ts), and check how many files get recompiled in the `build/` (check the timestamp of the `touch`)
- With the PR do the same.

Ideally, only the changed file should be recompiled in the build for both versions.

**Comment by jtlan** [comment]
Reassigning to @aicioara, who has done more work with the tooling than I have.

**Comment by aicioara** [comment]
Yeah, just test the above and it should be good to go.

**Comment by bluong** [comment]
In both scenarios, it seems we build all files.

**Comment by bluong** [comment]
Note that I will be attempting to move so that the Gruntfile.js file is a lot more clear than what it is now.  I have my own personal suspicions on how we set up our compiler, for instance, and while we will move to using Gulp likely, this cleanup should facilitate that migration.

**Comment by aicioara** [comment]
Sounds good

**Pull request merged**
