### PR TITLE
Use valueOf() when comparing to account for Date objects

### LINKED ISSUE #1689: Time scale locks up if domain is set to two equal values
http://jsfiddle.net/vhqwqwry/2/

Due to `Date` object equality checking.

### PR DESCRIPTION
**Pull request by jtlan**
Close #1689.

### CODE REVIEW

**Comment by bluong** [comment]
Do we want a test?  +1 otherwise

**Comment by jtlan** [comment]
I can add one, but I think `Domainer`s need a major overhaul.

**Comment by crmorford** [comment]
I don't actually see any behavior change from develop on this test. http://jsfiddle.net/ck1psjL3/9/

**Comment by jtlan** [comment]
@crmorford Setting the domain explicitly shuts off autodomaining, even if data changes. Try calling `xScale.autoDomain()` after adding data -- it doesn't work on **develop**.

**Pull request merged**
