### PR TITLE
[plottableMultifile] No longer using plottable multifile and relatives

### LINKED ISSUE #1093: Figure out why plottable_multifile.js doesn't load correctly.
Previously, tests were run using **plottable_multifile.js**, which split up the source code to make it easier to identify where code was executing during the tests. However, for reasons still unknown, on @endrjuskr 's computer loading the unit tests page with the multifile version of Plottable chokes.

The multifile version of Plottable simplifies debugging tests, so it would be nice to restore it. On the other hand, the single-file version is a more realistic test scenario.

### PR DESCRIPTION
**Pull request by aicioara**
Closes #1093 

This was no longer used. It was factored out in the grunt file refactor and now removed.

### CODE REVIEW

**Comment by aicioara** [comment]
NOQE as no source code changes

**Comment by bluong** [comment]
Can you remove the references to the multifiles from the .gitignore?

**Comment by aicioara** [comment]
I knew I was missing something :D

**Comment by aicioara** [comment]
wrong button. Waiting for it to compile again now...

**Pull request merged**
