### PR TITLE
TSLint breaks

### PR DESCRIPTION
**Pull request by aicioara**
Just an experiment...

### CODE REVIEW

**Comment by aicioara** [comment]
As you can see here https://travis-ci.org/palantir/plottable/builds/61378328 the build is failing because of a missing semicolon in `component.ts:14`. Which make sense.
However, if you `git checkout tslintBreak && grunt tslint`, you will see no errors. Why is that?

**Comment by aicioara** [comment]
@bluong you were looking into this. What's the status?

**Comment by bluong** [comment]
Let's move this discussion onto the develop branch so we can close out the branch

**Comment by bluong** [comment]
I'm seeing errors now.  I think this is resolved

**Comment by aicioara** [comment]
I still want to check something regarding this. Reassigning it to me to check this and not forget. Will close before Friday.

**Pull request closed without merging**
