### PR TITLE
[Plottable.css] - Cleaning useless declarations

### PR DESCRIPTION
**Pull request by bluong**
Quite a few declarations that we don't really document anywhere.

We should think about a way to document this better if possible

### CODE REVIEW

**Comment by aicioara** [comment]
Can't really check the correctness of these, since they are not documented. The code itself looks good, but I'd give it QE as well to make sure no funny business happening

**Comment by crmorford** [comment]
how are we sure no one is dependent on these styles?

**Comment by bluong** [comment]
@crmorford As discussed with @jtlan , we can't be sure on how no one is dependent.  We should just be sure that our own stylings work nicely with what we have declared ourselves (I am mainly removing these rules since there are 0 references to these rules in our codebase) and then provide the obsolete rules in the upgrade guide

**Comment by crmorford** [comment]
Cool, just note it in the upgrade instructions

**Pull request merged**
