### PR TITLE
XDragBoxLayer and YDragBoxLayer don't error when destroy()-ed.

### PR DESCRIPTION
**Pull request by bluong**

### CODE REVIEW

**Comment by jtlan** [comment]
Would it be better to just not have the `xScale()` and `yScale()` getters throw errors?

**Comment by bluong** [comment]
I didn't necessarily want to have a functional change to patch this up.  That said, I'm unsure what approach to take.

**Comment by crmorford** [comment]
This hotfix is about the error "XDragBoxLayer has no yScale" and vice versa, although you can't (and shouldn't) set the yScale. Correct?

**Comment by crmorford** [comment]
Anyway, here's something weird: http://jsfiddle.net/fee6p9w0/4/
The last line of the fiddle is "dragBoxLayer.destroy()", so it should be gone. But you can still drag and reach the call back .onDrag(), as evidenced by the console.logs.

**Comment by crmorford** [comment]
Summary (a la Justin)
User perspective: You should be able to call .destroy() without getting any errors.

**Comment by crmorford** [comment]
QE fiddles
DragBoxLayer http://jsfiddle.net/fee6p9w0/7/
SelectionBoxLayer http://jsfiddle.net/fee6p9w0/8/
XDragBoxLayer http://jsfiddle.net/fee6p9w0/9/
YDragBoxLayer http://jsfiddle.net/fee6p9w0/10/

**Comment by crmorford** [comment]
No errors, everything seems to work correctly whether xScale and yScale are set or not.

**Pull request merged**
