### PR TITLE
Fixes #1033 SVG visibility issues with Firefox

### LINKED ISSUE #1033: Setting SVG visibility to hidden does not completely hide on Firefox
Super specific yes.

screen shot 2014-09-12 at 2 47 56 pm

Here is a fiddle of the repro: http://jsfiddle.net/2a8y33q4/

### PR DESCRIPTION
**Pull request by rcchen**
Fixes #1033

### CODE REVIEW

**Comment by bluong** [comment]
Can you give a brief description in the PR for what the resolution is?  I'm curious myself.

**Comment by rcchen** [comment]
tl;dr changing the CSS class to inherit instead of visible, and then making sure that selectors are looking for anything that matches "visible" or "inherit" when selecting the pool of ticks that can be deselected from.

**Comment by rcchen** [comment]
This way the visibility of ticks is inherited from the parent SVG.

**Comment by crmorford** [comment]
Looks good! Congrats on your victory against IE.

**Pull request merged**
