### PR TITLE
Sed version for distributable. Update version in package for patch release.

### PR DESCRIPTION
**Pull request by themadcreator**

### CODE REVIEW

**Comment by themadcreator** [comment]
Fixes #3341
Fixes #3338

**Review by hellochar — APPROVED** [review]
I wonder, can we test this stuff as part of our build somehow?

**Comment by themadcreator** [comment]
We really should test all release modules and artifacts. But how to test those without releasing?

**Comment by hellochar** [comment]
Our unit tests didn't catch this P0 because we don't have any that tests the module loading. Maybe we could add a dumb nodejs test:

```js
// test-module-loading.js
var Plottable = require("plottable");
```

and run it with our build step:

```
// package.json
  "test-node": "node test-module-loading.js"
```

**Pull request merged**
