### PR TITLE
Enable 'object constancy' on data refresh by supporting a key function in Dataset

### PR DESCRIPTION
**Pull request by softwords**
see issue #2512 
This pull request 
- adds the key function to Dataset
- uses this key in Drawer when binding data to the selection
- provides 2 predefined keys:
-- NoConstancy - which will return a new value each time it is called, therefire ensuring that there is _never_ object constancy; that is, all elements in the selection are removed and recreated
-- ByIndex - returns the index of the datum n the array, which is the default behaviour of d3 anyway

- Also removes the logic on AnimateOnNextRender in ScatterPlot. This logic simulates the destruction and recreation of each svg element to create an animation effect. But, if the NoConstancy key is used, d3 destroys and recreates the svg elements itself, so there is no need for this workaround.
This also resolves issue #2707.

### CODE REVIEW

**Comment by bluong** [comment]
There seems to be a lot of drastic whitespace changes (due to indentation, seemingly).  Can you change the pull request such that the tabs stay consistent with the rest of the code base?

**Comment by softwords** [comment]
@bluong; >>drastic whitespace changes
yes I can see this now - it's a bit of a mess. I think the simplest path may be to start over

**Comment by bluong** [comment]
@softwords Feel free to reach out if you need any help in development!

**Comment by softwords** [comment]
@bluong thanks for the encouragement! I'll have another attempt to get this one ready, and get comfortable with the workflow.

**Pull request closed without merging**
