### PR TITLE
Release/2.8.0

### PR DESCRIPTION
**Pull request by themadcreator**

### CODE REVIEW

**Comment by themadcreator** [comment]
# Draft Notes



### Features
* Added `maxWidth` and `maxLinesPerEntry` for legends
* Added `maxTimeIntervalPrecision` for time axis tick precision.
* Exposed `isHorizontal` add `getScale` methods on axes.

### Performance
* Reduced unnecessary call to `computeLayout` in `renderTo`

### Housekeeping
* Add demo preview to all PRs

**Comment by 1calorie** [comment]
+1

**Comment by CalvinFernandez** [comment]
Lgtm

**Comment by themadcreator** [comment]
Test raw js https://jsfiddle.net/3yzhx4vy/

**Pull request merged**
