### PR TITLE
[JSHint] - removing from repo

### PR DESCRIPTION
**Pull request by bluong**
Now that we have a decently nice set of rules defined through eslint, I think it is safe to remove JSHint from the codebase so that we don't have multiple tools doing the same thing.  I'll continue to look into adding more rules to eslint, but that's in the future

### CODE REVIEW

**Comment by aicioara** [comment]
How about `jscs`? Shall we remove that as well?

**Comment by aicioara** [comment]
Please remove `.jshintrc`

**Comment by bluong** [comment]
`jscs` is decently special in that it only looks at code style, which is an area that is different than `jshint` and `eslint` to my understanding.

**Comment by aicioara** [comment]
Can't `eslint` do that? If not, then why? Linting is code style.

**Pull request merged**
