### PR TITLE
Drag Refactor

### LINKED ISSUE #1038: Dragbox should be drawn in foreground
Currently, `Interaction.Dragbox` and descendents draw the box in the background of the associated `Component`, which makes it impossible to see the box if it's behind an opaque bar or something. Drawing a transparent box in the foreground would solve this problem.

Might also be good to align with design on this one -- one suggestion was to fade out everything that wasn't in the box.

### LINKED ISSUE #1236: Interaction.Dragbox.setupZoomCallback() does not work
At all. Repro:
 1. Go to http://jsfiddle.net/7z6s4oyv/1/
 2. Attempt to click and drag inside the plot area.

Expected: Zooms in on drag area after releasing the mouse button.
Actual: Zooms wildly on beginning drag.

### LINKED ISSUE #1491: Zooming on IE9 causes Interaction.Dragbox to misalign
Repro: http://jsfiddle.net/fvsufoww/

Try drawing a dragbox, then zoom in with `Ctrl`+`+` and draw another dragbox. Note that the cursor position that `DragBox` responds to is up and to the right of the actual position.

Related to #1490, probably.

### LINKED ISSUE #1497: Interaction.Dragbox doesn't work with CSS scale() transforms
Applying a CSS `scale()` transform to a scatter plot breaks the dragbox interaction. It seems like the element doesn't project interactions to the scaled SVG coordinates.

Repro: http://jsfiddle.net/fvsufoww/3/

### LINKED ISSUE #1623: Reimplement Interaction.Drag
To use the new <svg>-wide dispatchers (#1588), and allow multiple `Drag` interactions on the same `<svg>`.

### LINKED ISSUE #1785: XDragBox, YDragBox don't stay full-height on resizing
**Repro**:
http://jsfiddle.net/ys23qtso/
1. Draw a box.
2. Click "resize" button.

**Expected**: drag-box stays the full height of the <svg>.
**Actual**: drag-box keeps its original height.

### PR DESCRIPTION
**Pull request by jtlan**
The Drag refactor is here!

I'm sorry this was so huge, but there wasn't a way to split it up without having half-broken things.

### `Interaction.Drag`
Works pretty much the same way, except for some renames:
* `dragstart()` --> `onDragStart()`
* `drag()` --> `onDrag()`
* `dragend()` --> `onDragEnd()`
* `setupZoomCallback` --> removed (it was broken anyway (#1236)).

Example fiddle: http://jsfiddle.net/fgns88L7/

### `Component.SelectionBoxLayer`
This `Component` draws a translucent box in the space it occupies. The bounds of the box can be set using the `bounds()` method:
```Typescript
bounds(newBounds: Bounds): SelectionBoxLayer;
```
A `Bounds` object is used to specify the location of the corners of the box:
```
/**
 * The corners of a box.
 */
export type Bounds = {
  topLeft: Point;
  bottomRight: Point;
}
```
The box can be shown or hidden using the `boxVisible()` method.

### `Interaction.DragBox` --> `Component.Interactive.DragBoxLayer`
Instead of attaching a `Interaction.DragBox` to a `Component`, instead create a `DragBoxLayer` and merge it with the `Component`(s). A `DragBoxLayer` is a subclass of `SelectionBoxLayer` with a `Interaction.Drag` already hooked up. A number of methods have been changed:
* `onDragStart()`, `onDrag()`, and `onDragEnd()` now set callbacks that take a `Bounds` object. The appropriate callbacks will be triggered when the bounds of the box are set by dragging.
Resizing can be enabled by calling `resizable(true)`, allowing the edges and corners of the box to be repositioned. The box can be resized if the user clicks close enough to an edge or corner: *how* close can be set using the `detectionRadius()` method.

Example fiddle: http://jsfiddle.net/zjL1eo49/1/
Using the box to zoom: http://jsfiddle.net/gr4k1qdk/

### `XDragBoxLayer` and `YDragBoxLayer`
Subclasses of `DragBoxLayer` that only allow selection in a single dimension.

Example fiddle: http://jsfiddle.net/c9focghu/1/

### Closed Tickets
Close #1038.
Close #1236.
Close #1491.
Close #1497.
Close #1623.
Close #1785.

### CODE REVIEW

**Comment by bluong** [comment]
Auto +1 from Dev.  I might still look through it if there's any weirdness

**Comment by jtlan** [comment]
Known issue on the first fiddle (http://jsfiddle.net/fgns88L7/) -- ending the drag outside the result IFrame will cause the drag to get confused. This doesn't happen without iFrames, and since the mouseUp event is never sent there's not really anything that can be done about it...

**Comment by crmorford** [comment]
http://jsfiddle.net/gr4k1qdk/ 
Click at (3, 2), drag to (5, 5) 
Low end of domain is 3 for both scales

**Comment by crmorford** [comment]
If you right-click, it will start a drag. We probably only want to start a drag on left click.

**Pull request merged**
