### PR TITLE
Upgrade to Typesettable@4.0.0

### PR DESCRIPTION
**Pull request by themadcreator**

### CODE REVIEW

**Comment by themadcreator** [comment]
The long labels example is particularly informative:
https://723-16149854-gh.circle-artifacts.com/0/home/ubuntu/plottable/quicktests/maxLabelWidth.html

**Comment by adidahiya** [comment]
no API breaks in this version of typesettable?

**Comment by adidahiya** [comment]
long labels example looks quite good!

**Comment by themadcreator** [comment]
This upgrade to typesettable doesn't break the plottable API but it does change the default text wrapping behavior of labels.

**Review by hellochar — APPROVED** [review]

**Pull request merged**
