### PR TITLE
[GridPlot] - getDrawer now returns a RectDrawer

### PR DESCRIPTION
**Pull request by bluong**
Used to create an ElementDrawer that sets its own svgElement to "rect"

### CODE REVIEW

**Comment by bluong** [comment]
Not sure if this should be NOQE, as a brief overlaying glance seems to show no changes

**Comment by jtlan** [comment]
Doesn't rectDrawer have some like label-drawing or bar-specific logic?

**Comment by bluong** [comment]
Only if the plot tells the drawer to draw labels (Also, we were considering moving that label logic out)

**Comment by crmorford** [comment]
Good it look

**Pull request merged**
