### PR TITLE
Closes issue #3132

### PR DESCRIPTION
**Pull request by mhamas**
Fixing typings for Line, allowing for flexible data type on the y-axis.

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/plottable](https://github.com/palantir/plottable), @mato93! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by CalvinFernandez** [comment]
@mato93 this is because you want a horizontal line chart, right?

**Review by CalvinFernandez — CHANGES_REQUESTED** [review]
the plottable.d.ts file is generated programmatically, instead make this change to `linePlot.ts`

review contributing guidelines for the process
https://github.com/palantir/plottable#contributing

**Comment by adidahiya** [comment]
Closing as stale

**Pull request closed without merging**
