### PR TITLE
[animatorRefactor] Forgoten animator quicktests fix

### PR DESCRIPTION
**Pull request by aicioara**

### CODE REVIEW

**Comment by bluong** [comment]
We may not want to do this until we merge the code into master.  @jtlan When do you think is the best timing to remove the guards?

**Comment by aicioara** [comment]
Hmm, I always removed the guards before committing to `develop` but I can see your point

**Comment by aicioara** [comment]
@crmorford thoughts?

**Comment by jtlan** [comment]
Wait for merge to **`master`**, so we can diff against it during the regression pass.

**Pull request closed without merging**
