### PR TITLE
Link to definitions in bower.json

### PR DESCRIPTION
**Pull request by jtlan**
As per "Link to bundled definitions" explained at https://github.com/DefinitelyTyped/tsd#link-to-bundled-definitions

### CODE REVIEW

**Comment by bluong** [comment]
Can we have someone test this or upload a screenshot testing that tsd works as above?

**Comment by aicioara** [comment]
Can you please provide more information here as per why is it needed, how do we use this, how come we could live without it before and what is the upside of having it.

Does it help us with automatically uploading to the tsd github or something?

**Comment by aicioara** [comment]
Codewise I approve

**Comment by bluong** [comment]
There is some tsd link command here
https://github.com/DefinitelyTyped/tsd#link-to-bundled-definitions

**Comment by jtlan** [comment]
After we add this line, running `tsd link` in the console of a project with a bower dependency on Plottable will add the following line to the project's **tsd.d.ts** file:
```
/// <reference path="../bower_components/plottable/plottable.d.ts" />
```

**Pull request merged**
