### PR TITLE
[Interactions.Key] - onKey -> onKeyPress

### PR DESCRIPTION
**Pull request by bluong**

### CODE REVIEW

**Comment by aicioara** [comment]
Do you want to take the entire ticket here as a PR https://github.com/palantir/plottable/issues/2268 ?

**Comment by bluong** [comment]
I would rather not.  Unitize as much as possible

**Comment by aicioara** [comment]
Don't forget to revert quicktests guards at the end

**Comment by bluong** [comment]
Should be done after the QE pass at the end

**Pull request merged**
